name: la_music
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.2

  flutter_bloc: 8.0.0
  bloc: 8.0.0
  equatable: 2.0.3

  auto_route: 3.1.3

  hive_flutter: 1.1.0
  hive_generator: 1.1.1

  intl: 0.17.0

  dio: 4.0.4
  get_it: 7.2.0
  injectable: 1.5.0
  retrofit: 3.0.0
  freezed: 1.1.0
  freezed_annotation: 1.1.0

  youtube_player_iframe: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0
  build_runner: 2.1.5
  injectable_generator: 1.5.2
  retrofit_generator: 3.0.0+2
  auto_route_generator: 3.1.0

flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
